### ISSUE TITLE
Replace epoch loop with per-request puncturing

### ISSUE THREAD

**Issue by NullHypothesis** [brave/star-randsrv#12]
We don't necessarily need an independent goroutine that periodically punctures our PPOPRF. We could simply call `getEpoch` in the request handler and puncture the PPOPRF if the returned epoch differs from the current epoch.

**Comment by rillian** [comment]
@NullHypothesis Do you still want to do this?

I agreed this would have been nice with the previous go implementation using mutexes. With the `RwLock` in the new code, I think having a background process is better. The complexity of the code required to avoid racing across the the update isn't an improvement.

**Comment by NullHypothesis** [comment]
Right, let's close this.
