### ISSUE TITLE
Add IP address-based rate limiting

### ISSUE THREAD

**Issue by NullHypothesis** [brave/star-randsrv#3]
This is going to protect the system from ourselves, i.e., we won't easily be able to brute force our way through Nested STAR.

**Comment by NullHypothesis** [comment]
Some more thoughts:

- We want verifiable rate limiting to prove to our users that it's difficult for us to brute force our way through the message space.
- Rate limiting outside the enclave is not user-verifiable.
- Rate limiting inside the enclave is verifiable but the enclave does not see client IP addresses; it only sees the EC2 host's VSOCK ID.
- For now, we may want to move forward with a global (instead of IP address-based) rate limiter. It's less useful but at least it's verifiable.

**Comment by rillian** [comment]
A couple of go rate limit modules:
- https://pkg.go.dev/golang.org/x/time/rate
- https://github.com/throttled/throttled
- https://github.com/ulule/limiter/
- https://github.com/sethvargo/go-limiter

Searching pkg.go.dev for 'rate limit' finds quite a few more.

**Comment by NullHypothesis** [comment]
> If we somehow make visible how many instances are sharing a particular key, a local, non-ip-based rate limit within each enclave instance would at least bound the traffic we can process. That way we couldn't hide extra capacity by using a small number of 16xlarge instances.

Makes sense, and I don't have a better idea for now. I already have a local branch that implements a rudimentary rate limiter based on Go's x/time package, so I'll repurpose that.

**Comment by rillian** [comment]
We seem to be doing ok without this. Closing as "not planned".
